spring.application.name=Knowledge-Nest
server.port=8081

# Disable automatic relational DB configuration
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#DB Configurations
spring.data.mongodb.uri=mongodb+srv://yasithabhanukac:yasithabhanukac@cluster0.2jkeysg.mongodb.net/knowledge_nest

spring.data.mongodb.auto-index-creation=true

# JWT Configuration
jwt.secret=supersecretkeysupersecretkeysupersecretkey
jwt.expiration=86400000

