spring.application.name=Knowledge-Nest
server.port=8081
logging.level.root=INFO

# Disable automatic relational DB configuration
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#DB Configurations
spring.data.mongodb.uri=mongodb+srv://gimashiishara2:ishara12345@cluster0.dqecnjc.mongodb.net/knowledge_nest?retryWrites=true&w=majority&appName=Cluster0
#spring.data.mongodb.uri=mongodb+srv://yasithabhanukac:bhanuka1234567890@cluster0.2jkeysg.mongodb.net/knowledge_nest?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.auto-index-creation=true

# JWT Configuration
jwt.secret=supersecretkeysupersecretkeysupersecretkey
jwt.expiration=86400000

# oauth configurations
# new
spring.security.oauth2.client.registration.google.client-id=333308065233-5o7u8epkrrtl6hdnr5a57ua6sg8ttoeq.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo