spring.application.name=Knowledge-Nest
server.port=8081

# Disable automatic relational DB configuration
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#DB Configurations
spring.data.mongodb.uri=mongodb+srv://gimashiishara2:ishara12345@cluster0.dqecnjc.mongodb.net/knowledge_nest?retryWrites=true&w=majority&appName=Cluster0

spring.data.mongodb.auto-index-creation=true

# oauth configurations


# JWT Configuration
jwt.secret=your-256-bit-secret-key-base64-encoded-make-this-very-secure
jwt.expiration=86400000
